spring:
  application:
    name: translation_streamer
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      security:
        protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080
  ssl:
    enabled: false

livekit:
  host: http://onliver.ru:7880
  apiKey: APIXMCTJEXDBghU
  secret: laxpDMZwSmNlxvjHzG8YnZsti8ofCMRlY9H6OAL7EeL

logging:
  level:
    ru.onliver.translation_streamer: INFO
    org.freedesktop.gstreamer: DEBUG

